In [19]:
import numpy as np
import clingo
from json import dumps
import re

In [20]:
def combine(encoding_path, benchmark_path, destination_path):
    
    combined_path = destination_path + "/combined_prep.lp"
    
    encoding_file = open(encoding_path, "r")
    encoding = encoding_file.read()
    encoding_file.close()
    
    benchmark_file = open(benchmark_path, "r")
    benchmark = benchmark_file.read()
    benchmark_file.close()
    
    combined_file = open(combined_path, "w")
    combined = combined_file.write(benchmark + encoding)
    combined_file.close()

In [21]:
enc2 = "./asprilo-encodings/prep/prep.lp"
abst = "./instances/adrian/benchmark2/CNC/cnc_instance.lp"
dest = "./python"
n=20
combine(enc2,abst,dest)

In [22]:
combined_path = dest + "/combined_prep.lp"
combined_file = open(combined_path, "r")
combined = combined_file.read()
combined_file.close()

In [23]:
solution = ""
md=[]
gr=[]
asp=combined
    
ctl = clingo.Control(['--stats'])
ctl.add("base", [], asp)
ctl.ground([("base", [])])
with ctl.solve(yield_=True) as handle:
    for m in handle: 
        solution=("{} ".format(m))
        #md=re.findall('md(.+?) ', ("{} ".format(m)))
        gr=re.findall('group(.+?) ', ("{} ".format(m)))
    handle.get()
print(dumps(ctl.statistics['summary']['times']['total'], sort_keys=True, indent=4, separators=(',', ': ')))

0.02864217758178711


In [24]:
print(gr)
#print(md)

['(1,1)', '(10,1)', '(4,1)', '(20,1)', '(2,2)', '(3,3)', '(2,3)', '(15,3)', '(4,4)', '(16,4)', '(5,5)', '(6,6)', '(18,6)', '(7,7)', '(20,7)', '(17,7)', '(8,8)', '(2,8)', '(7,8)', '(9,9)', '(18,9)', '(10,10)', '(11,11)', '(14,11)', '(18,11)', '(12,12)', '(20,12)', '(11,12)', '(14,12)', '(13,13)', '(14,14)', '(6,14)', '(15,15)', '(19,15)', '(2,15)', '(7,15)', '(16,16)', '(4,16)', '(19,16)', '(2,16)', '(17,17)', '(11,17)', '(6,18)', '(18,18)', '(19,19)', '(15,19)', '(3,19)', '(20,20)', '(18,20)', '(7,20)', '(17,20)', '(2,19)', '(7,19)', '(3,15)', '(18,14)', '(6,11)', '(20,10)', '(11,7)', '(19,4)', '(2,4)', '(19,3)', '(3,2)', '(15,2)', '(8,2)', '(7,2)', '(20,4)', '(14,6)', '(20,8)', '(1,10)', '(11,14)', '(7,17)', '(20,17)', '(14,18)', '(11,20)', '(12,20)', '(14,20)', '(16,19)', '(4,19)', '(14,17)', '(20,11)', '(4,10)', '(8,7)', '(2,7)', '(1,4)', '(10,4)', '(19,2)', '(15,7)', '(19,7)', '(12,11)', '(11,15)', '(11,18)', '(20,19)', '(12,14)', '(20,14)', '(7,11)', '(11,6)', '(16,2)', '(4,2)', '

In [25]:
cor = np.zeros((n,n), dtype=int)
for i in gr:
    x,y = map(int, i.strip('()').split(','))
    cor[x-1,y-1]=1
print(cor)   
groups=[]
for i in range(0,n):
    gr_=set()
    gr_.add(i+1)
    for j in range(0,n):
        if cor[i][j]==1:
            gr_.add(j+1)
    groups.append(gr_)
    
for i in range(len(groups)):
    groups[i] = list(groups[i])
    
groups = np.array(groups)
groups=np.unique(groups)
groups=groups.tolist()

[[1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]]


In [26]:
print(groups)

[[1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20], [5], [13]]
